# Generated by Django 5.0.1 on 2024-01-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UloadImage', models.ImageField(upload_to='app1/')),
            ],
        ),
    ]
