# Generated by Django 5.0.1 on 2024-01-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='UloadImage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
