# Generated by Django 5.0.1 on 2024-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_usermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
