# Generated by Django 5.0.1 on 2024-01-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_usermodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='Name',
        ),
    ]
